Tracking - don't show running time when stop is clicked
TypeError: runningEntry is null 3 popup.js:58:5
    getRunningDate moz-extension://68a96d7e-37b1-4c45-8c3d-2f1155e76306/src/popup.js:58
    showRunningTime moz-extension://68a96d7e-37b1-4c45-8c3d-2f1155e76306/src/popup.js:189